### ISSUE TITLE
Hello everyone, z_unpack.py How to use?

### ISSUE THREAD

**Issue by cokllbak** [TheCherry/ark-server-manager#1]
C:\Python27>python z_unpack.py "E:\Steam\steamapps\workshop\content\346110\481514565\WindowsNoEditor\AdvancedOrganizer_Large.uasset.z" "E:\Steam\steam
apps\workshop\content\346110\481514565\WindowsNoEditor\AdvancedOrganizer_Large.uasset"
Traceback (most recent call last):
  File "z_unpack.py", line 31, in <module>
    z_unpack(sys.argv[1], sys.argv[2])
  File "z_unpack.py", line 14, in z_unpack
    size1 = str_to_l(f_src.read(8))
  File "z_unpack.py", line 7, in str_to_l
    return struct.unpack('L', st)[0]
struct.error: unpack requires a string argument of length 4

C:\Python27>python z_unpack.py "E:\Steam\steamapps\workshop\content\346110\481514565\LinuxNoEditor\AdvancedOrganizer_Large.uasset.z" "E:\Steam\steamap
ps\workshop\content\346110\481514565\LinuxNoEditor\AdvancedOrganizer_Large.uasset"
Traceback (most recent call last):
  File "z_unpack.py", line 31, in <module>
    z_unpack(sys.argv[1], sys.argv[2])
  File "z_unpack.py", line 14, in z_unpack
    size1 = str_to_l(f_src.read(8))
  File "z_unpack.py", line 7, in str_to_l
    return struct.unpack('L', st)[0]
struct.error: unpack requires a string argument of length 4

**Comment by TheCherry** [comment]
seems that this is a windows issue, dont have a test system for that here.
Try to modify in line 7 the 

```
return struct.unpack('L', st)[0]
```

to

```
return struct.unpack('LL', st)[0]
```

or

```
return struct.unpack('q', st)[0]
```

If that work, I will update the script for windows.

**Comment by cokll** [comment]
I use
>return struct.unpack('LL', st)[0]
>return struct.unpack('q', st)[0]
error
>C:\Python27>python z_unpack.py "BerryJuicer.uasset.z.uasset.z" "BerryJuicer.uasset.z.uasset"
>  File "z_unpack.py", line 7
>    print st
 >       ^
>IndentationError: expected an indented block

**Comment by cokllbak** [comment]
Thank you very much, they can work.

**Comment by TheCherry** [comment]
Fixes #1 in https://github.com/TheCherry/ark-server-manager/commit/4eebf4e23ed62cce23bebf032194673ccfac714f
